sudo: required
language: java
jdk:
  - oraclejdk8
before_script:
  - wget http://services.gradle.org/distributions/gradle-5.0-bin.zip
  - unzip gradle-5.0-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.0
  - export PATH=$GRADLE_HOME/bin:$PATH
addons:
  chrome: stable
  sonarcloud:
    organization: at-08
    token:
      secure: "$SONAR_TOKEN"
before_install:
  - openssl aes-256-cbc -K $encrypted_7673b6e8444a_key -iv $encrypted_7673b6e8444a_iv
    -in environment.json.enc -out environment.json -d
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - gradle compileJava compileTestJava
  - sonar-scanner
  - gradle check
  - gradle executeFeatures
notifications:
  email: true

